package p025c8;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import p211d8.C9881e;
import p211d8.C9903u;
import p247h8.C10432b;

/* renamed from: c8.f */
/* compiled from: EncodedPath */
final class C6789f {
    /* renamed from: a */
    private static List<String> m38860a(String str) {
        int length = str.length();
        C10432b.m52648d(length >= 2, "Invalid path \"%s\"", str);
        if (length == 2) {
            C10432b.m52648d(str.charAt(0) == 1 && str.charAt(1) == 1, "Non-empty path \"%s\" had length 2", str);
            return Collections.emptyList();
        }
        int length2 = str.length() - 2;
        ArrayList arrayList = new ArrayList();
        StringBuilder sb = new StringBuilder();
        int i = 0;
        while (i < length) {
            int indexOf = str.indexOf(1, i);
            if (indexOf < 0 || indexOf > length2) {
                throw new IllegalArgumentException("Invalid encoded resource path: \"" + str + "\"");
            }
            int i2 = indexOf + 1;
            char charAt = str.charAt(i2);
            if (charAt == 1) {
                String substring = str.substring(i, indexOf);
                if (sb.length() != 0) {
                    sb.append(substring);
                    substring = sb.toString();
                    sb.setLength(0);
                }
                arrayList.add(substring);
            } else if (charAt == 16) {
                sb.append(str.substring(i, indexOf));
                sb.append(0);
            } else if (charAt == 17) {
                sb.append(str.substring(i, i2));
            } else {
                throw new IllegalArgumentException("Invalid encoded resource path: \"" + str + "\"");
            }
            i = indexOf + 2;
        }
        return arrayList;
    }

    /* renamed from: b */
    static C9903u m38861b(String str) {
        return C9903u.m50783v(m38860a(str));
    }

    /* renamed from: c */
    static <B extends C9881e<B>> String m38862c(B b) {
        StringBuilder sb = new StringBuilder();
        int r = b.mo32358r();
        for (int i = 0; i < r; i++) {
            if (sb.length() > 0) {
                m38864e(sb);
            }
            m38863d(b.mo32355o(i), sb);
        }
        m38864e(sb);
        return sb.toString();
    }

    /* renamed from: d */
    private static void m38863d(String str, StringBuilder sb) {
        int length = str.length();
        for (int i = 0; i < length; i++) {
            char charAt = str.charAt(i);
            if (charAt == 0) {
                sb.append(1);
                sb.append(16);
            } else if (charAt != 1) {
                sb.append(charAt);
            } else {
                sb.append(1);
                sb.append(17);
            }
        }
    }

    /* renamed from: e */
    private static void m38864e(StringBuilder sb) {
        sb.append(1);
        sb.append(1);
    }

    /* renamed from: f */
    static String m38865f(String str) {
        StringBuilder sb = new StringBuilder(str);
        int length = sb.length() - 1;
        char charAt = sb.charAt(length);
        C10432b.m52648d(charAt == 1, "successor may only operate on paths generated by encode", new Object[0]);
        sb.setCharAt(length, (char) (charAt + 1));
        return sb.toString();
    }
}
